services: docker
install: true

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

jobs:
  include:
    - stage: build
      script: ./travis-build.sh

notifications:
  email:
    on_success: never
    on_failure: always
