services: docker
install: true
language: python

branches:
  only:
    - master
    - dev

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

jobs:
  include:
    - stage: build
      script: ./travis-build.sh
    - stage: test
      script: docker run --rm opentransport/gtfs-exporter:dev  gtfs-process --provider=url --url=https://tursib.ro/trasee/gtfs --id=test


notifications:
  email:
    on_success: never
    on_failure: always
