services: docker
language: python

branches:
  only:
    - master
    - dev

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc


jobs:
  include:
    # run unit tests
    - stage: unit-tests
      before_install:
        - pip install poetry
      install:
        - poetry install
      script: pytest

    # build container
    - stage: deploy
      script: ./travis-build.sh
       # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master

    # run integration tests
    - stage: integration-tests
      script: docker run --rm opentransport/gtfs-exporter:dev  gtfs-process --provider=url --url=https://tursib.ro/trasee/gtfs --id=test
