name: Process master push or pr
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        poetry-version: [1.1.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install & Unit test
        run: |
          poetry install
          poetry run py.test
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image from master and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
      - name: Integration test
        run: docker run --rm opentransport/gtfs-exporter  gtfs-process --provider=url --url=https://tursib.ro/trasee/gtfs --id=test
